### ISSUE TITLE
Error: ...\aapt.exe package --auto-add-overlay -v -f -m -J gen -...

### ISSUE THREAD

**Issue by samjoly** [TuneOSS/unity-plugin#6]
When compiling a simple test project to Android with the version v4.1.1 with Unity 5.3.4f1
It gives me this error:

> Error building Player: CommandInvokationFailure: Failed to re-package resources. See the Console for details.
> ...\AppData\Local\Android\android-sdk\build-tools\23.0.3\aapt.exe package --auto-add-overlay -v -f -m -J gen -M AndroidManifest.xml -S "res" -I ".../AppData/Local/Android/android-sdk\platforms\android-23\android.jar" -F bin/resources.ap_ --extra-packages com.google.vr.cardboard:com.google.android.gms:com.google.android.gms:vr.gvr.platform.unity -S "...\Temp\StagingArea\android-libraries\cardboard_android_common\res" -S "...\Temp\StagingArea\android-libraries\google-play-services_lib\res" -S "...\Temp\StagingArea\android-libraries\play-services-basement-9.0.1\res" -S "...\Temp\StagingArea\android-libraries\unityvractivity\res"

I ended up using the version v4.0.1

**Comment by john-gu** [comment]
This may be an issue of duplicate res folders being used. With v4.1.1 we now try to use the play-services-basement 9.0.1 aar. Do you have `/google-play-services_lib` and `/google-play-services_lib/res` folders in your `Plugins/Android` which may be causing collision?
