### ISSUE TITLE
App crashes on lower Android api devices in Unity Plugin

### ISSUE THREAD

**Issue by samrajsingh** [TuneOSS/unity-plugin#9]
I am using the Unity version of Tune
But the app crashes on Android Api (4.4.2) while it works properly on Upper Android apis.

android.java.exception java.lang.NoClassDefFoundError:de.greenrobot.event.EventBus
com.tune.ma.eventbus.TuneEventBus.(TuneEventBus.Java:18)
com.tune.Tune.init(Tune.java:175).

An clue about this??

**Comment by samrajsingh** [comment]
Any update on this topic??

**Comment by HasRonald** [comment]
Hi, we are currently looking into your issue.  We'll update you once we find the solution to this.

Thanks

**Comment by samrajsingh** [comment]
Hey @HasRonald  , 
The issue is fixed now . It was a multidexing issue rather a greenbot on lower api issue.
Thank you for your concern.

Sam
